"""Give every agent definition the gates it does not inherit.

  python ~/.claude/scripts/inject_agent_gates.py --plan
  python ~/.claude/scripts/inject_agent_gates.py --apply

AGENTS.md's own subagent clause says subagents don't inherit that file. This writes
the short version straight into each agents/*.md, right after the frontmatter.
Idempotent: reruns replace the block instead of stacking copies.
"""
import argparse
import os
import re

AGENTS = os.path.join(os.path.expanduser(r"~/.claude"), "agents")
START = "<!-- GATES:START — generated by scripts/inject_agent_gates.py, do not hand-edit -->"
END = "<!-- GATES:END -->"

BLOCK = f"""{START}
## Gates (binding — you do not inherit `AGENTS.md`, so they are restated here)

**G2 THINK.** State assumptions out loud; two readings → present both, never pick silently.
Simplest thing that works — no unrequested features, abstractions, or configurability.
Surgical edits: every touched line traces to the request. MERGE, never replace.
Define "done" as a checkable condition before you act.

**G3 ACT.** Destructive ops (delete, overwrite, reset, force-push, live migration) need Karim's
confirmation first and a backup under `_backups/` — never `/tmp`, never a delete on `C:`.
Never read, print, or commit `.env`, keys, or tokens. Arabic-first for content and social,
English for code and infra. Someone else's repo open in Karim's IDE → hand back a paste-ready
prompt, don't edit it yourself.

**G4 VERIFY — the one that gets skipped.** Before you report done, point at the artifact that
proves it: test output, screenshot, rendered file, curl response, deployed URL. Exercise the
change end to end. Tests fail → quote the failure verbatim. Cannot prove it → write
"unverified" plainly. Never pad a gap with a plausible guess.

**Claims.** Every factual claim carries its source. Numbers come from real data you can point
to, never from recall.

**Return contract.** Your final message IS the deliverable — no preamble, no "I hope this
helps". Lead with the answer, then the evidence.
{END}"""


def files():
    return sorted(f for f in os.listdir(AGENTS) if f.endswith(".md"))


def inject(text):
    """Insert (or refresh) the block immediately after the YAML frontmatter."""
    if START in text:
        return re.sub(re.escape(START) + r".*?" + re.escape(END), BLOCK, text, flags=re.S)
    m = re.match(r"^(---\n.*?\n---\n)", text, flags=re.S)
    if not m:
        return None
    head = m.group(1)
    return head + "\n" + BLOCK + "\n" + text[len(head):].lstrip("\n")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--plan", action="store_true")
    ap.add_argument("--apply", action="store_true")
    a = ap.parse_args()

    changed, skipped, already = [], [], []
    for f in files():
        p = os.path.join(AGENTS, f)
        with open(p, encoding="utf-8") as fh:
            text = fh.read()
        new = inject(text)
        if new is None:
            skipped.append(f + " (no frontmatter)")
            continue
        if new == text:
            already.append(f)
            continue
        if a.apply:
            with open(p, "w", encoding="utf-8") as fh:
                fh.write(new)
        changed.append(f)

    verb = "injected" if a.apply else "would inject"
    print(f"{verb}: {len(changed)}   unchanged: {len(already)}   skipped: {len(skipped)}")
    for f in changed:
        print("  +", f)
    for f in skipped:
        print("  !", f)
    if not a.apply:
        print("\n(plan only — rerun with --apply)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
