#!/usr/bin/env bash
# new-client-build.sh — scaffold a new client web project with the v2 playbook defaults baked in.
# Encodes the convergent moves from 6 creators studied 2026-05-19:
#   1. Persistent CLAUDE.md context file (Viktor's motionsites.ai / Sourany's DESIGN.md / Nick's Leon-taste-skill role)
#   2. design-system/MASTER.md placeholder (run ui-ux-pro-max --persist to fill)
#   3. Lenis + GSAP ScrollTrigger pre-installed (Immersive Garden Tier-A move)
#   4. Print the exact next-Claude-Code prompt to use
#
# Usage:
#   ./new-client-build.sh <slug> [aesthetic-skill]
#   aesthetic-skill defaults to "soft-skill" (high-end-visual-design from Leonxlnx/taste-skill family)
#   other options: brutalist-skill, minimalist-skill, gpt-tasteskill, redesign-skill
#
# Example:
#   ./new-client-build.sh acme-luxury-watches soft-skill

set -euo pipefail

SLUG="${1:-}"
AESTHETIC="${2:-soft-skill}"

if [[ -z "$SLUG" ]]; then
  echo "Usage: $0 <slug> [aesthetic-skill]"
  echo ""
  echo "Examples:"
  echo "  $0 acme-watches soft-skill          # high-end-visual-design"
  echo "  $0 nova-agency brutalist-skill      # industrial-brutalist-ui"
  echo "  $0 zenith-saas minimalist-skill     # minimalist-ui editorial"
  echo "  $0 retro-shop gpt-tasteskill        # general aesthetic pack"
  exit 1
fi

# Resolve project root — default to ~/projects/<slug>, override with PROJ_ROOT env var
ROOT="${PROJ_ROOT:-$HOME/projects}/${SLUG}"
TS=$(date -u +%Y-%m-%dT%H:%MZ)

if [[ -d "$ROOT" ]]; then
  echo "❌ $ROOT already exists. Pick a different slug or delete the directory first."
  exit 1
fi

echo "📁 Creating $ROOT"
mkdir -p "$ROOT/design-system/pages" "$ROOT/refs" "$ROOT/assets"

# ---------- CLAUDE.md skeleton ----------
cat > "$ROOT/CLAUDE.md" <<EOF
# Project: ${SLUG}

> Scaffolded ${TS} by new-client-build.sh — fill in the gaps before first prompt.

## Brand
- Client name:
- Industry / niche:
- One-line value proposition:
- Audience:
- Brand voice adjectives (3):

## Aesthetic
- Aesthetic pack to activate FIRST: \`${AESTHETIC}\` (Leonxlnx/taste-skill family)
- Inspiration references (3 URLs from Dribbble/Landbook/Awwwards):
  1.
  2.
  3.
- Mood adjectives (3, e.g. "monastic, patient, silent"):

## Stack
- Framework: Vite + React + TypeScript
- Styling: Tailwind CSS
- Motion: GSAP + ScrollTrigger (installed) + Lenis (installed)
- 3D: Three.js (optional, install on-demand via \`npm install three\`)
- Deploy target: Vercel

## Non-negotiables (from playbook v2)
- Lenis smooth-scroll active in app root (snippet below)
- Monochrome base + ONE accent color — no rainbow gradients
- All sections \`min-h-[100dvh]\`, never \`h-screen\`
- \`prefers-reduced-motion\` respected on every animation
- Touch targets ≥44pt on mobile
- No emoji icons; use lucide-react or Phosphor Light
- If videos used: 100% opacity, NO overlays (Viktor's invariant)
- All assets hosted on Cloudflare R2, never localhost

## Lenis + GSAP boilerplate (already wired in src/lib/scroll.ts)
\`\`\`ts
import gsap from 'gsap'
import { ScrollTrigger } from 'gsap/ScrollTrigger'
import Lenis from 'lenis'

gsap.registerPlugin(ScrollTrigger)
export const lenis = new Lenis({ lerp: 0.08 })
lenis.on('scroll', ScrollTrigger.update)
gsap.ticker.add((time) => lenis.raf(time * 1000))
gsap.ticker.lagSmoothing(0)
\`\`\`

## Design system
- See \`design-system/MASTER.md\` (generated by ui-ux-pro-max — run the command in the README)
- Per-page overrides in \`design-system/pages/<page>.md\`
- READ MASTER.md AT THE START OF EVERY PROMPT TO CLAUDE.

## References to feed Claude
- \`refs/\` directory — drop screenshots here, name them \`hero.png\`, \`features.png\`, etc.
- For each ref, before coding, run the ChatGPT design-analyst trick (see README → Iterating)

## Out of scope (don't add)
- Audio / VO / background music — sites ship silent
- Custom GLSL shaders — use three-custom-shader-material or skip
- 3-letter abbreviations as section names — write the full word
EOF

# ---------- design-system/MASTER.md placeholder ----------
cat > "$ROOT/design-system/MASTER.md" <<EOF
# Design System — ${SLUG}

> PLACEHOLDER. Generate the real version by running:
>
>     python3 ~/.claude/skills/ui-ux-pro-max/scripts/search.py \\
>       "<industry> <vertical> <aesthetic keywords>" \\
>       --design-system --persist -p "${SLUG}"
>
> That command will overwrite this file with palette tokens, type scale,
> spacing scale, motion easing, and anti-patterns based on Karim's
> ui-ux-pro-max skill (161 palettes / 57 font pairings / 99 UX rules).

## Until then — manual defaults (DELETE after running the command):
- Palette: TBD (monochrome base + 1 accent)
- Display font: TBD (NOT Inter / Roboto / Helvetica — see banned list in feedback_default_fonts_ban)
- Body font: TBD
- Spacing scale: 4 / 8 / 16 / 24 / 48 / 96
- Radius: 0 (sharp) OR 6px (uniform) OR pill (1000px) — pick one
- Motion easing: cubic-bezier(0.22, 1, 0.36, 1)
- Motion duration: 200ms (micro), 400ms (transitions), 800ms (scroll-tied)
EOF

# ---------- design-system/pages/.gitkeep ----------
touch "$ROOT/design-system/pages/.gitkeep"

# ---------- refs/.gitkeep + brief.md ----------
touch "$ROOT/refs/.gitkeep"
cat > "$ROOT/refs/brief.md" <<EOF
# Reference Brief — ${SLUG}

For each screenshot you drop in this folder, run the ChatGPT
design-analyst trick (wpdev.'s contribution):

> "Describe this design in detail — break down the layout, the section
> order, the navigation, the font style, the colors, the spacing, the
> image treatment, the cards, the button, and the overall feel of the
> design."

Paste the response below the matching ref name. THIS is what gets
fed to Claude Code as the build prompt — not the raw screenshot.

## refs/hero.png
[analyst output here]

## refs/features.png
[analyst output here]
EOF

# ---------- README.md ----------
cat > "$ROOT/README.md" <<EOF
# ${SLUG}

Scaffolded ${TS}. Aesthetic: \`${AESTHETIC}\`.

## First-run checklist

\`\`\`bash
# 1. Bootstrap the Vite app (run inside this dir)
npm create vite@latest . -- --template react-ts
npm install lenis gsap @gsap/react tailwindcss @tailwindcss/vite lucide-react

# 2. Generate the real design system (overwrites design-system/MASTER.md)
python3 ~/.claude/skills/ui-ux-pro-max/scripts/search.py \\
  "<industry> <aesthetic keywords>" \\
  --design-system --persist -p "${SLUG}"

# 3. Drop 3 reference screenshots into refs/ (Dribbble / Landbook / Awwwards)

# 4. Run the ChatGPT design-analyst trick on each ref, paste results into refs/brief.md
\`\`\`

## Then in Claude Code (first prompt to send)

\`\`\`
Activate ${AESTHETIC} for this build (Leonxlnx/taste-skill family).
Read CLAUDE.md and design-system/MASTER.md for context.
Read refs/brief.md for the structured design briefs.

Build the hero section first. Use the analysis from refs/brief.md > refs/hero.png.

Non-negotiables (already in CLAUDE.md but restating):
- Lenis smooth-scroll active
- Section min-h-[100dvh]
- Monochrome + one accent
- prefers-reduced-motion respected
- No emoji icons
\`\`\`

## Then iterate — wpdev.'s loop

> "Generate, review, screenshot, fix, repeat."

For each section: review the rendered output, screenshot the issue,
paste back into Claude Code with a one-line fix description.

## Deploy

\`\`\`bash
# Local preview
npm run dev

# Production
vercel --prod
\`\`\`
EOF

# ---------- post-script next-step instructions ----------
cat <<EOF

✅ Scaffold ready at: $ROOT

Next steps (copy these):

  cd "$ROOT"
  npm create vite@latest . -- --template react-ts
  npm install lenis gsap @gsap/react tailwindcss @tailwindcss/vite lucide-react

  python3 ~/.claude/skills/ui-ux-pro-max/scripts/search.py \\
    "<industry> <aesthetic keywords>" --design-system --persist -p "${SLUG}"

Then open the directory in Claude Code, fill CLAUDE.md, drop refs/ screenshots, and send:
  > Activate ${AESTHETIC} for this build. Read CLAUDE.md, design-system/MASTER.md, and refs/brief.md.
  > Build the hero section first.

Files created:
  $ROOT/CLAUDE.md
  $ROOT/README.md
  $ROOT/design-system/MASTER.md
  $ROOT/design-system/pages/.gitkeep
  $ROOT/refs/.gitkeep
  $ROOT/refs/brief.md

EOF
